# Generated by Django 5.2.11

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def set_book_slugs(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        if not book.slug:
            base = slugify(book.title) or f'book-{book.id}'
            book.slug = base
            cnt = 0
            while Book.objects.filter(slug=book.slug).exclude(pk=book.pk).exists():
                cnt += 1
                book.slug = f'{base}-{cnt}'
            book.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='demo_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_new_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='table_of_contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookcategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='final_exam_id',
            field=models.UUIDField(blank=True, help_text='Public ID of linked Exam (exams.Exam). No FK to avoid migration dependency.', null=True),
        ),
        migrations.RunPython(set_book_slugs),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='book',
                    name='slug',
                    field=models.SlugField(max_length=255, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'books_book_slug_unique') THEN ALTER TABLE books_book ADD CONSTRAINT books_book_slug_unique UNIQUE (slug); END IF; END $$;",
                    reverse_sql="ALTER TABLE books_book DROP CONSTRAINT IF EXISTS books_book_slug_unique;",
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'verbose_name': 'Book Chapter',
                'verbose_name_plural': 'Book Chapters',
                'ordering': ['book', 'order'],
            },
        ),
        migrations.AddField(
            model_name='userbookpurchase',
            name='pdf_folder_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userbookpurchase',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbookpurchase',
            name='pdf_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserChapterProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='books.bookchapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chapter Progress',
                'verbose_name_plural': 'User Chapter Progresses',
            },
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='books_bookchapter_unique_book_order'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('book', 'slug'), name='books_bookchapter_unique_book_slug'),
        ),
        migrations.AddConstraint(
            model_name='userchapterprogress',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='books_userchapterprogress_unique_user_chapter'),
        ),
    ]
