# Generated by Django 5.2.11 on 2026-02-22 02:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookcategory_chapters_purchase_extras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookchapter',
            name='books_bookchapter_unique_book_order',
        ),
        migrations.RemoveConstraint(
            model_name='bookchapter',
            name='books_bookchapter_unique_book_slug',
        ),
        migrations.RemoveConstraint(
            model_name='userbookpurchase',
            name='books_userbookpurchase_unique_user_book',
        ),
        migrations.RemoveConstraint(
            model_name='userchapterprogress',
            name='books_userchapterprogress_unique_user_chapter',
        ),
        migrations.AlterUniqueTogether(
            name='bookchapter',
            unique_together={('book', 'order'), ('book', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookpurchase',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userchapterprogress',
            unique_together={('user', 'chapter')},
        ),
    ]
