# Generated by Django 5.2.11 on 2026-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='book_chapters/'),
        ),
    ]
