# Generated by Django 5.2.11 on 2026-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookchapter_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterprogress',
            name='current_page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
