# Generated by Django 5.2.11 on 2026-02-27 13:38

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_current_page_to_user_chapter_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.book_cover_upload_to),
        ),
    ]
