# Generated by Django 5.2.11 on 2026-02-27 13:41

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=books.models.book_chapter_upload_to),
        ),
    ]
