# Generated by Django 5.2.12 on 2026-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_add_admin_stats_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userchapterprogress',
            name='ucp_last_read_idx',
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='encrypted_cdn_url',
            field=models.URLField(blank=True, help_text='Public URL of the AES-256-GCM encrypted PDF on Supabase CDN. Null if not yet encrypted.', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='encryption_version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented on every re-upload. Included in IV derivation to prevent GCM nonce reuse.'),
        ),
    ]
