# Generated by Django 5.2.12 on 2026-03-23 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_userchapterprogress_ucp_last_read_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['user', 'last_read'], name='idx_ucp_user_last_read'),
        ),
    ]
