# Generated by Django 5.2.13 on 2026-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_userchapterprogress_idx_ucp_user_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='small_cover',
            field=models.CharField(blank=True, help_text='Public Bunny CDN URL for resized WebP cover (auto-generated). Do not edit manually.', max_length=500),
        ),
    ]
