# Generated by Django 5.2.15 on 2026-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_small_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If False, only owners (purchased or VIP) can see this book in lists and detail.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_lt',
            field=models.PositiveIntegerField(default=500, help_text='Price in LT (in-app currency)'),
        ),
    ]
