# Generated by Django 5.2.11 on 2026-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECHARGE_VOUCHER', 'Recharge via Voucher'), ('PURCHASE_BOOK', 'Purchase Book'), ('PURCHASE_VIDEO', 'Purchase Video'), ('ADMIN_EDIT', 'Admin Edit'), ('ADMIN_TOPUP', 'Admin Top-up'), ('VIP_SUBSCRIPTION', 'VIP Subscription')], max_length=30),
        ),
    ]
