# Generated by Django 5.2.11 on 2026-02-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_content_cff8bd_idx',
            old_name='comments_co_content_8c2a0d_idx',
        ),
    ]
