export enum QuestionType {
    TRUE_FALSE = 'TRUE_FALSE',
    MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
    MULTIPLE_ANSWER = 'MULTIPLE_ANSWER',
    MATCHING = 'MATCHING',
    ORDERING = 'ORDERING',
}
