# Generated by Django 5.2.13 on 2026-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookIntroPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sidebar_qr_image', models.URLField(blank=True)),
                ('sidebar_zalo_url', models.URLField()),
                ('chapters', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Book Intro Page',
                'verbose_name_plural': 'Book Intro Pages',
            },
        ),
    ]
