# Generated by Django 5.2.15 on 2026-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookintropage',
            name='qr_image_upload',
            field=models.ImageField(blank=True, help_text='Upload a QR image here. It will be converted to WebP and stored on Bunny CDN automatically.', null=True, upload_to='landing/qr_upload/'),
        ),
        migrations.AlterField(
            model_name='bookintropage',
            name='sidebar_qr_image',
            field=models.URLField(blank=True, help_text='Public Bunny CDN URL for the QR image (auto-filled on upload). Do not edit manually.'),
        ),
    ]
