# Generated by Django 5.2.15 on 2026-06-12 08:34

import django.db.models.deletion
import transcripts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_transcriptconfig_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name, e.g. key-phuc-personal, key-work', max_length=100)),
                ('api_key', transcripts.fields.EncryptedCharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to pause key without deleting it')),
                ('request_count', models.PositiveIntegerField(default=0, help_text='Total requests used across all models (never resets)')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini API Key',
                'verbose_name_plural': 'Gemini API Keys',
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='transcriptconfig',
            name='model',
            field=models.CharField(choices=[('gemini-3.5-flash', 'Gemini 3.5 Flash'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], default='gemini-2.5-flash', max_length=100),
        ),
        migrations.CreateModel(
            name='TranscriptApiKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='e.g. gemini-2.5-flash, gemini-file-api', max_length=100)),
                ('rpd_count', models.PositiveIntegerField(default=0, help_text='Requests used today for this model')),
                ('rpd_reset_at', models.DateTimeField(help_text='When rpd_count resets (midnight UTC)')),
                ('exhausted_until', models.DateTimeField(blank=True, help_text='Set on 429. Null = available.', null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='transcripts.transcriptapikey')),
            ],
            options={
                'verbose_name': 'API Key Usage',
                'verbose_name_plural': 'API Key Usages',
                'unique_together': {('api_key', 'model_name')},
            },
        ),
    ]
