# Generated by Django 5.2.15 on 2026-06-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_api_key_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='gemini_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transcripts.transcriptapikey'),
        ),
    ]
