# Generated by Django 5.2.15 on 2026-06-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_gemini_api_key_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='step2b_warning',
            field=models.TextField(blank=True, default='', help_text='Warning message if transcript appears incomplete. Does not fail the job.'),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='transcript_coverage',
            field=models.FloatField(blank=True, help_text='Ratio of last transcript timestamp / audio duration (0.0–1.0). Null if not verified.', null=True),
        ),
        migrations.AlterField(
            model_name='transcriptconfig',
            name='model',
            field=models.CharField(choices=[('gemini-3.5-flash', 'Gemini 3.5 Flash'), ('gemini-3-flash-preview', 'Gemini 3 Flash'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], default='gemini-2.5-flash', max_length=100),
        ),
    ]
