# Generated by Django 5.2.15 on 2026-06-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0006_update_transcript_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='step1_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step1_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step2a_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step2a_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step2b_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step2b_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step3_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptjob',
            name='step3_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
