# Generated by Django 5.2.15 on 2026-06-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0007_step_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='step2b_model',
            field=models.CharField(blank=True, default='', help_text='Gemini model used for last step 2b run', max_length=100),
        ),
    ]
