# Generated by Django 5.2.11

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('price_lt', models.PositiveIntegerField(default=0, help_text='Price in Linh Thạch (LT)')),
            ],
            options={
                'verbose_name': 'Video Course',
                'verbose_name_plural': 'Video Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_purchases', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='videos.videocourse')),
            ],
            options={
                'verbose_name': 'User Video Purchase',
                'verbose_name_plural': 'User Video Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='uservideopurchase',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='videos_uservideopurchase_unique_user_video'),
        ),
    ]
