# Generated by Django 5.2.11

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def set_course_slugs(apps, schema_editor):
    VideoCourse = apps.get_model('videos', 'VideoCourse')
    for course in VideoCourse.objects.all():
        if not getattr(course, 'slug', None):
            base = slugify(course.title) or f'course-{course.id}'
            course.slug = base
            cnt = 0
            while VideoCourse.objects.filter(slug=course.slug).exclude(pk=course.pk).exists():
                cnt += 1
                course.slug = f'{base}-{cnt}'
            course.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='videocourse',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='videos.videocategory'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='instructor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='total_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='final_exam_id',
            field=models.UUIDField(blank=True, help_text='Public ID of linked Exam (exams.Exam). No FK to avoid migration dependency.', null=True),
        ),
        migrations.RunPython(set_course_slugs),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='videocourse',
                    name='slug',
                    field=models.SlugField(max_length=255, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'videos_videocourse_slug_unique') THEN ALTER TABLE videos_videocourse ADD CONSTRAINT videos_videocourse_slug_unique UNIQUE (slug); END IF; END $$;",
                    reverse_sql="ALTER TABLE videos_videocourse DROP CONSTRAINT IF EXISTS videos_videocourse_slug_unique;",
                ),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('video_id', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('is_free', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='videos.videocourse')),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='videos.videolesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lesson Progress',
                'verbose_name_plural': 'User Lesson Progresses',
            },
        ),
        migrations.AddConstraint(
            model_name='videolesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='videos_videolesson_unique_course_order'),
        ),
        migrations.AddConstraint(
            model_name='videolesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='videos_videolesson_unique_course_slug'),
        ),
        migrations.AddConstraint(
            model_name='userlessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='videos_userlessonprogress_unique_user_lesson'),
        ),
    ]
