# Generated by Django 5.2.11 on 2026-02-22 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_categories_lessons_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userlessonprogress',
            name='videos_userlessonprogress_unique_user_lesson',
        ),
        migrations.RemoveConstraint(
            model_name='uservideopurchase',
            name='videos_uservideopurchase_unique_user_video',
        ),
        migrations.RemoveConstraint(
            model_name='videolesson',
            name='videos_videolesson_unique_course_order',
        ),
        migrations.RemoveConstraint(
            model_name='videolesson',
            name='videos_videolesson_unique_course_slug',
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='uservideopurchase',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='videolesson',
            unique_together={('course', 'order'), ('course', 'slug')},
        ),
    ]
