# Generated by Django 5.2.11 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_userlessonprogress_videos_userlessonprogress_unique_user_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
