# Generated by Django 5.2.11 on 2026-02-27 13:41

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_thumbnail_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.lesson_thumbnail_upload_to),
        ),
    ]
