# Generated by Django 5.2.12 on 2026-03-15 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_add_admin_stats_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Course Progress',
                'verbose_name_plural': 'User Course Progresses',
            },
        ),
        migrations.RemoveIndex(
            model_name='userlessonprogress',
            name='ulp_last_watched_idx',
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='videos.videocourse'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videolesson'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
    ]
