# Generated by Django 5.2.12 on 2026-03-23 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_usercourseprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'last_watched'], name='idx_ulp_user_last_watched'),
        ),
    ]
