# Generated by Django 5.2.12 on 2026-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_userlessonprogress_idx_ulp_user_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='infographic_pdf_key',
            field=models.CharField(blank=True, help_text='Bunny Storage key. Auto-populated when uploading via admin. Max 50 MB.', max_length=255, verbose_name='Lược đồ PDF (Bunny key)'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='infographic_video_url',
            field=models.CharField(blank=True, help_text='Summary video URL (Bunny embed URL or iframe src). Paste direct URL.', max_length=500, verbose_name='Video tóm tắt URL'),
        ),
    ]
