# Generated by Django 5.2.13 on 2026-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_add_infographic_fields_to_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='small_thumbnail',
            field=models.CharField(blank=True, help_text='Public Bunny CDN URL for resized WebP thumbnail (auto-generated). Do not edit manually.', max_length=500),
        ),
    ]
