# Generated by Django 5.2.15 on 2026-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_videolesson_small_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If False, only owners (purchased or VIP) can see this course in lists and detail.'),
        ),
    ]
