# Generated by Django 5.2.15 on 2026-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_videocourse_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='bunny_collection_id',
            field=models.CharField(blank=True, help_text="Bunny Stream collection GUID that this course's lessons belong to. Run `sync_bunny_collection` to apply it to the lessons on Bunny.", max_length=64, verbose_name='Bunny Collection ID'),
        ),
    ]
