# Generated by Django 5.2.11 on 2026-02-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('videos', '0004_thumbnail_imagefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order'], 'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='videos.videolesson'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(blank=True, help_text='Nhãn hiển thị trên thẻ, vd: KHÁI NIỆM CỐT LÕI', max_length=100),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='videos.videolesson'),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Trắc nghiệm nhiều lựa chọn'), ('YES_NO', 'Có / Không'), ('TRUE_FALSE', 'Đúng / Sai')], default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Score %% to pass'),
        ),
    ]
