# Generated by Django 5.2.11 on 2026-02-28 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookchapter_file_path'),
        ('exams', '0002_alter_flashcard_options_exam_lesson_and_more'),
        ('videos', '0005_alter_videolesson_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('FLASHCARD', 'Flashcard Deck'), ('QUIZ', 'Quiz / Exam')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Training Activity',
                'verbose_name_plural': 'Training Activities',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exam',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='exams.trainingactivity'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='exams.trainingactivity'),
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_set', to='books.bookchapter')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_set', to='videos.videolesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sets', to='exams.practicemodule')),
            ],
            options={
                'verbose_name': 'Training Set',
                'verbose_name_plural': 'Training Sets',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='training_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='exams.trainingset'),
        ),
        migrations.AddConstraint(
            model_name='trainingset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chapter_id__isnull', True), ('lesson_id__isnull', False), ('module_id__isnull', True)), models.Q(('chapter_id__isnull', False), ('lesson_id__isnull', True), ('module_id__isnull', True)), models.Q(('chapter_id__isnull', True), ('lesson_id__isnull', True), ('module_id__isnull', False)), _connector='OR'), name='trainingset_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='trainingactivity',
            constraint=models.UniqueConstraint(fields=('training_set', 'activity_type'), name='exams_trainingactivity_unique_type_per_set'),
        ),
    ]
