# Generated by Django 5.2.15 on 2026-08-30 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('version_code', models.PositiveIntegerField(help_text='Số sau dấu + trong pubspec.yaml (buildNumber). Chỉ tăng, không dùng lại.')),
                ('version_name', models.CharField(help_text='Ví dụ 1.2.0. Chỉ để hiển thị, không dùng để so sánh.', max_length=32)),
                ('min_supported_version_code', models.PositiveIntegerField(default=0, help_text='Client thấp hơn số này bị chặn. Bằng version_code = bản này bắt buộc.')),
                ('file', models.FileField(help_text='APK cho Android, IPA cho iOS.', upload_to='releases/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('release_notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Chỉ bản đã publish mới được endpoint trả về.')),
            ],
            options={
                'verbose_name': 'App Release',
                'verbose_name_plural': 'App Releases',
                'ordering': ['platform', '-version_code'],
                'indexes': [models.Index(fields=['platform', 'is_published', '-version_code'], name='idx_apprelease_lookup')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'version_code'), name='uniq_app_release_version_per_platform'), models.CheckConstraint(condition=models.Q(('min_supported_version_code__lte', models.F('version_code'))), name='app_release_floor_below_ceiling')],
            },
        ),
    ]
