# Generated by Django 5.2.17 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apprelease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprelease',
            name='file',
        ),
        migrations.AddField(
            model_name='apprelease',
            name='bunny_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
