# Generated by Django 5.2.13 on 2026-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_category',
            field=models.CharField(choices=[('CURRENCY', 'Currency Edit'), ('VIP_MANAGEMENT', 'VIP Upgrade/Downgrade'), ('DEVICE_RESET', 'Device Un-link'), ('CONTENT_GRANT', 'Manual Content Grant'), ('USER_ACTIVATION', 'User Account Activation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
