# Generated by Django 5.2.15 on 2026-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='geo_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='geo_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='geo_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='geo_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
