# Generated by Django 5.2.15 on 2026-08-30 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdevice_geo_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-last_active'], 'verbose_name': 'Web Device', 'verbose_name_plural': 'Web Devices'},
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_max_devices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_category',
            field=models.CharField(choices=[('CURRENCY', 'Currency Edit'), ('VIP_MANAGEMENT', 'VIP Upgrade/Downgrade'), ('DEVICE_RESET', 'Device Un-link'), ('CONTENT_GRANT', 'Manual Content Grant'), ('USER_ACTIVATION', 'User Account Activation'), ('MOBILE_SLOT', 'Mobile Device Slot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('WEB', 'Web')], max_length=20),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_region', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('geo_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('client_code', models.CharField(max_length=16, unique=True)),
                ('pairing_code', models.CharField(max_length=20, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hardware_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('issued_reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('claim_attempts', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('device_model', models.CharField(blank=True, max_length=128, null=True)),
                ('os_version', models.CharField(blank=True, max_length=64, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('ADMIN_UNBIND', 'Admin unbind'), ('MOBILE_DISABLED', 'Mobile access turned off')], max_length=20, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_mobile_slots', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_mobiledevice_user_status'), models.Index(fields=['status', 'expires_at'], name='idx_mobiledevice_expiry')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('device_id__isnull', False), ('status__in', ('UNCLAIMED', 'ACTIVE'))), fields=('user', 'device_id'), name='uniq_mobile_device_id_per_user'), models.UniqueConstraint(condition=models.Q(('hardware_hash__isnull', False), ('status__in', ('UNCLAIMED', 'ACTIVE'))), fields=('user', 'hardware_hash'), name='uniq_mobile_hardware_per_user')],
            },
        ),
    ]
