# Generated by Django 5.2.15 on 2026-08-27 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdevice_geo_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-last_active'], 'verbose_name': 'Web Device', 'verbose_name_plural': 'Web Devices'},
        ),
        migrations.AddField(
            model_name='userdevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_category',
            field=models.CharField(choices=[('CURRENCY', 'Currency Edit'), ('VIP_MANAGEMENT', 'VIP Upgrade/Downgrade'), ('DEVICE_RESET', 'Device Un-link'), ('CONTENT_GRANT', 'Manual Content Grant'), ('USER_ACTIVATION', 'User Account Activation'), ('DEVICE_ACTIVATION', 'Device Activation Key')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('WEB', 'Web')], max_length=20),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_region', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('geo_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('client_code', models.CharField(max_length=16, unique=True)),
                ('hardware_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('device_model', models.CharField(blank=True, max_length=128, null=True)),
                ('os_version', models.CharField(blank=True, max_length=64, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('ADMIN_UNBIND', 'Admin unbind'), ('REPLACED', 'Replaced by another handset')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='DeviceActivationKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('USED', 'Used'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=10)),
                ('issued_reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_activation_keys', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_activation_keys', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_keys', to=settings.AUTH_USER_MODEL)),
                ('used_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.mobiledevice')),
            ],
            options={
                'verbose_name': 'Device Activation Key',
                'verbose_name_plural': 'Device Activation Keys',
                'ordering': ['-created_at'],
                'permissions': [('view_activation_key_secret', 'Can view the plaintext activation key')],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', 'status'], name='idx_mobiledevice_user_status'),
        ),
        migrations.AddConstraint(
            model_name='mobiledevice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='uniq_active_mobile_device_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mobiledevice',
            constraint=models.UniqueConstraint(condition=models.Q(('hardware_hash__isnull', False)), fields=('user', 'hardware_hash'), name='uniq_mobile_hardware_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='mobiledevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddConstraint(
            model_name='deviceactivationkey',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('user',), name='uniq_issued_activation_key_per_user'),
        ),
    ]
