# Generated by Django 5.2.17 on 2026-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mobile_device_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_review_account',
            field=models.BooleanField(default=False),
        ),
    ]
